name: AxKills
version: '${project.version}'
main: com.artillexstudios.axkills.AxKills
api-version: '1.21'
folia-supported: true
softdepend:
  - PlaceholderAPI

commands:
  axkills:
    usage: /<command> <reload|toggle>

permissions:
  axkills.reload:
    default: op
  axkills.toggle:
    description: Allows the player to toggle death messages
    default: true