name: KillMessages
version: '${project.version}'
main: dev.thrior.killmessages.KillMessages
api-version: '1.21'
folia-supported: true
softdepend:
  - PlaceholderAPI

commands:
  killmessages:
    usage: /<command> <reload|toggle>

permissions:
  killmessages.reload:
    default: op
  killmessages.toggle:
    description: Allows the player to toggle death messages
    default: true